package me.aipao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRun<M extends BaseRun<M>> extends Model<M> implements IBean {

	public void setImei(java.lang.String imei) {
		set("imei", imei);
	}

	public java.lang.String getImei() {
		return get("imei");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setRunId(java.lang.String runId) {
		set("runId", runId);
	}

	public java.lang.String getRunId() {
		return get("runId");
	}

	public void setFieldId(java.lang.Integer fieldId) {
		set("fieldId", fieldId);
	}

	public java.lang.Integer getFieldId() {
		return get("fieldId");
	}

	public void setLastLat(java.lang.Float lastLat) {
		set("lastLat", lastLat);
	}

	public java.lang.Float getLastLat() {
		return get("lastLat");
	}

	public void setLastLng(java.lang.Float lastLng) {
		set("lastLng", lastLng);
	}

	public java.lang.Float getLastLng() {
		return get("lastLng");
	}

	public void setLat(java.lang.Float lat) {
		set("lat", lat);
	}

	public java.lang.Float getLat() {
		return get("lat");
	}

	public void setLng(java.lang.Float lng) {
		set("lng", lng);
	}

	public java.lang.Float getLng() {
		return get("lng");
	}

	public void setScores(java.lang.Integer scores) {
		set("scores", scores);
	}

	public java.lang.Integer getScores() {
		return get("scores");
	}

	public void setCoins(java.lang.Integer coins) {
		set("coins", coins);
	}

	public java.lang.Integer getCoins() {
		return get("coins");
	}

	public void setTime(java.lang.Integer time) {
		set("time", time);
	}

	public java.lang.Integer getTime() {
		return get("time");
	}

	public void setLength(java.lang.Integer length) {
		set("length", length);
	}

	public java.lang.Integer getLength() {
		return get("length");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}

	public java.lang.String getResult() {
		return get("result");
	}

}
