package me.aipao.model;

import me.aipao.model.base.BaseRun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Run extends BaseRun<Run> {
	public static final Run dao = new Run();
}
